/**
 * PDF Template: University Classic
 * Traditional Indian university examination paper format
 */
export function universityClassicTemplate(data: {
  institutionName: string;
  departmentName: string;
  courseName: string;
  courseCode: string;
  semester: number;
  examType: string;
  date: string;
  totalMarks: number;
  duration: number;
  instructions: string;
  sections: {
    title: string;
    questions: {
      number: number;
      text: string;
      marks: number;
      isCompulsory: boolean;
    }[];
  }[];
  logoUrl?: string;
}): string {
  const sectionHtml = data.sections
    .map(
      (section) => `
    <div class="section">
      <h3 class="section-title">${section.title}</h3>
      <table class="question-table">
        <tbody>
          ${section.questions
            .map(
              (q) => `
            <tr>
              <td class="q-num">${q.number}.</td>
              <td class="q-text">${q.text}</td>
              <td class="q-marks">[${q.marks}]</td>
            </tr>
          `
            )
            .join("")}
        </tbody>
      </table>
    </div>
  `
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  
  * { margin: 0; padding: 0; box-sizing: border-box; }
  
  body {
    font-family: 'Inter', 'Times New Roman', serif;
    font-size: 12pt;
    line-height: 1.5;
    color: #1a1a1a;
    padding: 20mm 15mm;
  }

  .header {
    text-align: center;
    border-bottom: 3px double #333;
    padding-bottom: 12px;
    margin-bottom: 16px;
  }

  .header .logo { width: 60px; height: 60px; margin-bottom: 6px; }
  .header .institution { font-size: 18pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }
  .header .department { font-size: 12pt; font-weight: 500; margin-top: 2px; }
  .header .exam-title { font-size: 14pt; font-weight: 600; margin-top: 8px; text-decoration: underline; }

  .meta-bar {
    display: flex;
    justify-content: space-between;
    border: 1px solid #333;
    padding: 8px 12px;
    margin-bottom: 16px;
    font-size: 11pt;
  }

  .meta-bar .left, .meta-bar .right { display: flex; flex-direction: column; gap: 2px; }
  .meta-bar strong { font-weight: 600; }

  .instructions {
    border: 1px solid #ccc;
    padding: 10px 14px;
    margin-bottom: 20px;
    background: #f9f9f9;
    font-size: 10pt;
  }

  .instructions h4 {
    font-weight: 600;
    margin-bottom: 6px;
    text-transform: uppercase;
    font-size: 10pt;
  }

  .section { margin-bottom: 24px; }

  .section-title {
    font-size: 13pt;
    font-weight: 700;
    text-transform: uppercase;
    border-bottom: 2px solid #333;
    padding-bottom: 4px;
    margin-bottom: 12px;
  }

  .question-table { width: 100%; border-collapse: collapse; }
  
  .question-table td {
    padding: 8px 4px;
    vertical-align: top;
    border-bottom: 1px dotted #ddd;
  }

  .q-num { width: 30px; font-weight: 600; }
  .q-text { padding-right: 12px; }
  .q-marks { width: 50px; text-align: right; font-weight: 600; color: #555; white-space: nowrap; }

  .footer {
    position: fixed;
    bottom: 15mm;
    left: 15mm;
    right: 15mm;
    display: flex;
    justify-content: space-between;
    font-size: 9pt;
    color: #666;
    border-top: 1px solid #ddd;
    padding-top: 6px;
  }

  @media print {
    body { padding: 0; }
    .page-break { page-break-before: always; }
  }
</style>
</head>
<body>
  <div class="header">
    ${data.logoUrl ? `<img src="${data.logoUrl}" class="logo" alt="Logo" />` : ""}
    <div class="institution">${data.institutionName}</div>
    <div class="department">Department of ${data.departmentName}</div>
    <div class="exam-title">${data.examType} Examination</div>
  </div>

  <div class="meta-bar">
    <div class="left">
      <span><strong>Subject:</strong> ${data.courseName} (${data.courseCode})</span>
      <span><strong>Semester:</strong> ${data.semester}</span>
      <span><strong>Date:</strong> ${data.date}</span>
    </div>
    <div class="right" style="text-align: right;">
      <span><strong>Max Marks:</strong> ${data.totalMarks}</span>
      <span><strong>Duration:</strong> ${data.duration} minutes</span>
    </div>
  </div>

  <div class="instructions">
    <h4>Instructions to Candidates</h4>
    ${data.instructions}
  </div>

  ${sectionHtml}

  <div class="footer">
    <span>Generated by QPG — Question Paper Generator</span>
    <span>Page 1</span>
  </div>
</body>
</html>`;
}

/**
 * PDF Template: Modern Clean
 * Minimalist design with subtle color accents
 */
export function modernCleanTemplate(data: {
  institutionName: string;
  departmentName: string;
  courseName: string;
  courseCode: string;
  semester: number;
  examType: string;
  date: string;
  totalMarks: number;
  duration: number;
  instructions: string;
  sections: {
    title: string;
    questions: {
      number: number;
      text: string;
      marks: number;
      isCompulsory: boolean;
    }[];
  }[];
  logoUrl?: string;
}): string {
  const sectionHtml = data.sections
    .map(
      (section) => `
    <div class="section">
      <div class="section-header">${section.title}</div>
      ${section.questions
        .map(
          (q) => `
        <div class="question">
          <span class="q-number">${q.number}</span>
          <div class="q-content">
            <div class="q-text">${q.text}</div>
          </div>
          <span class="q-marks">${q.marks}M</span>
        </div>
      `
        )
        .join("")}
    </div>
  `
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');
  
  * { margin: 0; padding: 0; box-sizing: border-box; }
  
  body {
    font-family: 'Plus Jakarta Sans', sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1e293b;
    padding: 24mm 18mm;
  }

  .header {
    display: flex;
    align-items: center;
    gap: 16px;
    padding-bottom: 16px;
    border-bottom: 2px solid #4f46e5;
    margin-bottom: 20px;
  }

  .header-logo {
    width: 56px;
    height: 56px;
    background: linear-gradient(135deg, #4f46e5, #6366f1);
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 20pt;
    font-weight: 700;
  }

  .header-text .institution { font-size: 16pt; font-weight: 700; color: #1e1b4b; }
  .header-text .subtitle { font-size: 10pt; color: #6b7280; }

  .meta-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 12px;
    margin-bottom: 20px;
  }

  .meta-item {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 10px 14px;
  }

  .meta-item .label { font-size: 9pt; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.5px; }
  .meta-item .value { font-size: 12pt; font-weight: 600; color: #1e293b; }

  .instructions {
    background: #eff6ff;
    border-left: 3px solid #4f46e5;
    padding: 12px 16px;
    margin-bottom: 24px;
    border-radius: 0 8px 8px 0;
    font-size: 10pt;
    color: #475569;
  }

  .section { margin-bottom: 28px; }

  .section-header {
    font-size: 12pt;
    font-weight: 700;
    color: #4f46e5;
    padding: 8px 14px;
    background: #eef2ff;
    border-radius: 8px;
    margin-bottom: 12px;
  }

  .question {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    padding: 10px 14px;
    margin-bottom: 6px;
    border-radius: 6px;
    transition: background 0.2s;
  }

  .question:hover { background: #f8fafc; }

  .q-number {
    width: 28px;
    height: 28px;
    background: #f1f5f9;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 10pt;
    font-weight: 600;
    color: #4f46e5;
    flex-shrink: 0;
  }

  .q-content { flex: 1; }
  .q-text { font-size: 11pt; }

  .q-marks {
    background: #4f46e5;
    color: white;
    padding: 2px 10px;
    border-radius: 12px;
    font-size: 9pt;
    font-weight: 600;
    flex-shrink: 0;
  }

  .footer {
    position: fixed;
    bottom: 18mm;
    left: 18mm;
    right: 18mm;
    text-align: center;
    font-size: 8pt;
    color: #94a3b8;
  }
</style>
</head>
<body>
  <div class="header">
    <div class="header-logo">${data.institutionName.charAt(0)}</div>
    <div class="header-text">
      <div class="institution">${data.institutionName}</div>
      <div class="subtitle">${data.departmentName} · ${data.examType} Examination</div>
    </div>
  </div>

  <div class="meta-grid">
    <div class="meta-item">
      <div class="label">Subject</div>
      <div class="value">${data.courseName}</div>
    </div>
    <div class="meta-item">
      <div class="label">Code</div>
      <div class="value">${data.courseCode}</div>
    </div>
    <div class="meta-item">
      <div class="label">Semester</div>
      <div class="value">${data.semester}</div>
    </div>
    <div class="meta-item">
      <div class="label">Date</div>
      <div class="value">${data.date}</div>
    </div>
    <div class="meta-item">
      <div class="label">Max Marks</div>
      <div class="value">${data.totalMarks}</div>
    </div>
    <div class="meta-item">
      <div class="label">Duration</div>
      <div class="value">${data.duration} min</div>
    </div>
  </div>

  <div class="instructions">
    <strong>Instructions:</strong> ${data.instructions}
  </div>

  ${sectionHtml}

  <div class="footer">
    Generated by QPG — Question Paper Generator · Confidential
  </div>
</body>
</html>`;
}

/**
 * PDF Template: Board/Government Style
 * Traditional Indian board examination format
 */
export function boardStyleTemplate(data: {
  institutionName: string;
  departmentName: string;
  courseName: string;
  courseCode: string;
  semester: number;
  examType: string;
  date: string;
  totalMarks: number;
  duration: number;
  instructions: string;
  sections: {
    title: string;
    questions: {
      number: number;
      text: string;
      marks: number;
      isCompulsory: boolean;
    }[];
  }[];
  logoUrl?: string;
}): string {
  const sectionHtml = data.sections
    .map(
      (section) => `
    <div class="section">
      <div class="section-title">${section.title}</div>
      ${section.questions
        .map(
          (q) => `
        <div class="question-row">
          <div class="q-num">${q.number}.</div>
          <div class="q-body">${q.text}</div>
          <div class="q-marks">${q.marks}</div>
        </div>
      `
        )
        .join("")}
    </div>
  `
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  
  body {
    font-family: 'Times New Roman', serif;
    font-size: 12pt;
    line-height: 1.6;
    padding: 18mm 15mm;
  }

  .header {
    text-align: center;
    border: 2px solid #000;
    padding: 14px;
    margin-bottom: 14px;
  }

  .header .institution {
    font-size: 18pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 2px;
  }

  .header .department {
    font-size: 12pt;
    font-weight: bold;
    margin-top: 4px;
  }

  .header .exam-title {
    font-size: 14pt;
    font-weight: bold;
    margin-top: 8px;
    text-decoration: underline;
    text-transform: uppercase;
  }

  .info-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 14px;
    border: 1px solid #000;
  }

  .info-table td {
    border: 1px solid #000;
    padding: 6px 10px;
    font-size: 11pt;
  }

  .info-table .label { font-weight: bold; width: 120px; background: #f0f0f0; }

  .instructions {
    border: 1px solid #000;
    padding: 10px;
    margin-bottom: 18px;
    font-size: 10pt;
  }

  .instructions .title {
    font-weight: bold;
    text-decoration: underline;
    margin-bottom: 6px;
  }

  .section { margin-bottom: 20px; }

  .section-title {
    font-size: 12pt;
    font-weight: bold;
    text-align: center;
    text-transform: uppercase;
    text-decoration: underline;
    margin-bottom: 12px;
    padding: 4px;
    background: #f0f0f0;
  }

  .question-row {
    display: flex;
    gap: 8px;
    padding: 6px 0;
    border-bottom: 1px solid #e0e0e0;
  }

  .q-num { width: 30px; font-weight: bold; }
  .q-body { flex: 1; }
  .q-marks { width: 60px; text-align: center; font-weight: bold; }

  .marks-header {
    display: flex;
    justify-content: flex-end;
    font-weight: bold;
    font-size: 10pt;
    margin-bottom: 4px;
    padding-right: 10px;
  }

  .watermark {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) rotate(-30deg);
    font-size: 60pt;
    color: rgba(0, 0, 0, 0.04);
    font-weight: bold;
    text-transform: uppercase;
    pointer-events: none;
    z-index: -1;
  }
</style>
</head>
<body>
  <div class="watermark">CONFIDENTIAL</div>

  <div class="header">
    <div class="institution">${data.institutionName}</div>
    <div class="department">${data.departmentName}</div>
    <div class="exam-title">${data.examType} Examination</div>
  </div>

  <table class="info-table">
    <tr>
      <td class="label">Subject</td>
      <td>${data.courseName} (${data.courseCode})</td>
      <td class="label">Date</td>
      <td>${data.date}</td>
    </tr>
    <tr>
      <td class="label">Semester</td>
      <td>${data.semester}</td>
      <td class="label">Max Marks</td>
      <td>${data.totalMarks}</td>
    </tr>
    <tr>
      <td class="label">Duration</td>
      <td colspan="3">${data.duration} minutes</td>
    </tr>
  </table>

  <div class="instructions">
    <div class="title">Note / Instructions:</div>
    ${data.instructions}
  </div>

  <div class="marks-header">Marks →</div>

  ${sectionHtml}

  <div style="text-align: center; margin-top: 30px; font-size: 10pt; font-weight: bold;">
    *** END OF QUESTION PAPER ***
  </div>
</body>
</html>`;
}
